# Uncomment this line to define a global platform for your project
platform :ios, '8.1'

source 'https://github.com/CocoaPods/Specs.git'

target 'NearBy' do

pod 'EstimoteSDK'
pod 'AFNetworking', '~> 2.5'

end

target 'NearByTests' do

end

